<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#11.Ridge,-Lasso,-Elastic-선형회귀분석-과제" data-toc-modified-id="11.Ridge,-Lasso,-Elastic-선형회귀분석-과제-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>11.Ridge, Lasso, Elastic 선형회귀분석 과제</a></span><ul class="toc-item"><li><span><a href="#전처리-:--id,-date-삭제" data-toc-modified-id="전처리-:--id,-date-삭제-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>전처리 :  id, date 삭제</a></span></li><li><span><a href="#범주형-변수-전처리" data-toc-modified-id="범주형-변수-전처리-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>범주형 변수 전처리</a></span></li><li><span><a href="#종속변수-y-=-price-,-나머지는-독립변수-X로-설정" data-toc-modified-id="종속변수-y-=-price-,-나머지는-독립변수-X로-설정-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>종속변수 y = price , 나머지는 독립변수 X로 설정</a></span></li><li><span><a href="#홀드아웃-기법을-사용하여-데이터-분할" data-toc-modified-id="홀드아웃-기법을-사용하여-데이터-분할-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>홀드아웃 기법을 사용하여 데이터 분할</a></span></li><li><span><a href="#Ridge-회귀분석을-하여-R2-값과-RMSE값을-구하고-설명하세요." data-toc-modified-id="Ridge-회귀분석을-하여-R2-값과-RMSE값을-구하고-설명하세요.-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Ridge 회귀분석을 하여 R2 값과 RMSE값을 구하고 설명하세요.</a></span></li><li><span><a href="#스케일링-한-데이터셋의-결과와-스케일링-하지-않은-데이터-셋의-결과를-비교해보세요." data-toc-modified-id="스케일링-한-데이터셋의-결과와-스케일링-하지-않은-데이터-셋의-결과를-비교해보세요.-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>스케일링 한 데이터셋의 결과와 스케일링 하지 않은 데이터 셋의 결과를 비교해보세요.</a></span></li><li><span><a href="#회귀-계수-중-집값과-상관성이-높은-3가지-변수를-해석하세요" data-toc-modified-id="회귀-계수-중-집값과-상관성이-높은-3가지-변수를-해석하세요-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>회귀 계수 중 집값과 상관성이 높은 3가지 변수를 해석하세요</a></span></li></ul></li></ul></div>

# 11.Ridge, Lasso, Elastic 선형회귀분석 과제

변수 설명 

id - 판매된 각 주택의 고유 ID <br>
date  - 주택 판매 날짜<br>
price - 판매된 각 주택의 가격<br>
bedrooms  - 침실 수<br>
bathrooms  - 화장실이 있지만 샤워 시설은 없는 방을 0.5로 설명하는 욕실 수<br>
sqft_living - 아파트 내부 생활 공간의 평방 피트<br>
sqft_lot - 토지 공간의 평방 피트수<br>
floors  - 층 수<br>
waterfront - 아파트가 해안가를 내려다보고 있는지 여부에 대한 더미 변수 - 범주형<br>
view - 부동산에 대한 뷰가 얼마나 좋았는지에 대한 0에서 4 사이의 인덱스 - 범주형<br>
condition - 아파트 상태에 대한 1에서 5까지의 지수, - 범주형 <br>
grade - 1-13까지의 수로,1-3은 건축 및 설계 미달, 7은 시공 및 설계 평균, 11-13은 시공 및 설계 수준 높은 수준이다. - 범주형<br>
sqft_above - 지면보다 높은 내부 주택 공간의 평방 피트수<br>
sqft_basement - 지면 아래에 있는 내부 주택 공간의 평방 피트수<br>
yr_built - 집이 처음 지어진 연도<br>
yr_renovated - 집의 마지막 리모델링 연도<br>
sqft_living15 - 가장 가까운 이웃 15명을 위한 내부 주택 생활 공간의 평방 피트<br>
sqft_lot15 - 가장 가까운 15개 이웃 토지 부지의 평방 피트수<br>

In [1]:
import pandas as pd 
df = pd.read_csv("data/kc_house_data.csv")
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,standard,0,3,7,1180,0,1955,0,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,standard,0,3,7,2170,400,1951,1991,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,standard,0,3,6,770,0,1933,0,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,standard,0,5,7,1050,910,1965,0,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,standard,0,3,8,1680,0,1987,0,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,standard,0,3,8,1530,0,2009,0,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,standard,0,3,8,2310,0,2014,0,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,standard,0,3,7,1020,0,2009,0,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,standard,0,3,8,1600,0,2004,0,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,standard,0,3,7,1020,0,2008,0,1020,1357

## 전처리 :  id, date 삭제

In [2]:
df = df.drop(['id', 'date'], axis = 1)

## 범주형 변수 전처리

In [10]:
df.info()
df.waterfront.value_counts()
df.view.value_counts()
df.condition.value_counts()
df.grade.value_counts()
df = pd.get_dummies(df, columns = ['waterfront', 'view', 'condition','grade'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21613 non-null  float64
 1   bedrooms       21613 non-null  int64
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64
 4   sqft_lot       21613 non-null  int64
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  object
 7   view           21613 non-null  int64
 8   condition      21613 non-null  int64
 9   grade          21613 non-null  int64
 10  sqft_above     21613 non-null  int64
 11  sqft_basement  21613 non-null  int64
 12  yr_built       21613 non-null  int64
 13  yr_renovated   21613 non-null  int64
 14  sqft_living15  21613 non-null  int64
 15  sqft_lot15     21613 non-null  int64
dtypes: float64(3), int64(12), object(1)
memory usage: 2.6+ MB

In [11]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,sqft_above,sqft_basement,yr_built,yr_renovated,...,grade_4,grade_5,grade_6,grade_7,grade_8,grade_9,grade_10,grade_11,grade_12,grade_13
0,221900.0,3,1.00,1180,5650,1.0,1180,0,1955,0,...,0,0,0,1,0,0,0,0,0,0
1,538000.0,3,2.25,2570,7242,2.0,2170,400,1951,1991,...,0,0,0,1,0,0,0,0,0,0
2,180000.0,2,1.00,770,10000,1.0,770,0,1933,0,...,0,0,1,0,0,0,0,0,0,0
3,604000.0,4,3.00,1960,5000,1.0,1050,910,1965,0,...,0,0,0,1,0,0,0,0,0,0
4,510000.0,3,2.00,1680,8080,1.0,1680,0,1987,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,1530,0,2009,0,...,0,0,0,0,1,0,0,0,0,0
21609,400000.0,4,2.50,2310,5813,2.0,2310,0,2014,0,...,0,0,0,0,1,0,0,0,0,0
21610,402101.0,2,0.75,1020,1350,2.0,1020,0,2009,0,...,0,0,0,1,0,0,0,0,0,0
21611,400000.0,3,2.50,1600,2388,2.0,1600,0,2004,0,...,0,0,0,0,1,0,0,0,0,0
21612,325000.0,2,0.75,1020,1076,2.0,1020,0,2008,0,...,0,0,0,1,0,0,0,0,0,0

## 종속변수 y = price , 나머지는 독립변수 X로 설정

In [12]:
X = df.drop(['price'], axis = 1)
y = df['price']

In [14]:
y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

## 홀드아웃 기법을 사용하여 데이터 분할

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 0)

## Ridge 회귀분석을 하여 R2 값과 RMSE값을 구하고 설명하세요.

In [17]:
import warnings
warnings.filterwarnings(action = 'ignore')

from sklearn.linear_model import Ridge

ridge = Ridge()
ridge.fit(X_train, y_train)

Ridge()

In [19]:
import numpy as np
print("사용한 데이터 컬럼 수 : ", np.sum(ridge.coef_!=0))
print("훈련 데이터 셋 성능 : ", ridge.score(X_train, y_train))
print("테스트 데이터 셋 성능 : ", ridge.score(X_test, y_test))

사용한 데이터 컬럼 수 :  35
훈련 데이터 셋 성능 :  0.6846018053071162
테스트 데이터 셋 성능 :  0.6757421119430622

In [20]:
# alpha 1로 하였을 경우, R2는 0.675임을 알 수 있다.

In [22]:
from sklearn.model_selection import GridSearchCV

ridge = Ridge()
param_grid = {'alpha':(0.0001,0.0005,0.001,0.005, 0.01,0.05,0.1, 0.15, 0.2, 0.25, 0.3,0.5,1,2,3)}
model = GridSearchCV(ridge, param_grid)
model.fit(X_train, y_train)

GridSearchCV(estimator=Ridge(),
             param_grid={'alpha': (0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 1, 2, 3)})

In [24]:
model.best_estimator_ # 이전과 동일하다.

Ridge(alpha=1)

In [25]:
y_pred = model.predict(X_test)

In [26]:
import numpy as np
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(mse)
print(rmse)

44517998284.94448
210992.88681124887

In [27]:
# rmse 210,992으로 확인된다. 이는 예측값과 실제값과 210,992만큼 차이가 날 수 있다.

## 스케일링 한 데이터셋의 결과와 스케일링 하지 않은 데이터 셋의 결과를 비교해보세요.
> Tip : X_train 데이터를 fit_transform 하여 전처리, X_test는 transform 사용하여 전처리 <br>
>  X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train),columns=X_train.columns,index=X_train.index)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

train_X_scaled = scaler.fit_transform(X_train)

In [30]:
train_X_scaled

array([[ 0.67170039, -0.79711466, -0.74522967, ..., -0.1390576 ,
        -0.0646653 , -0.02697424],
       [-0.38696772, -0.79711466, -0.68028398, ..., -0.1390576 ,
        -0.0646653 , -0.02697424],
       [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.1390576 ,
        -0.0646653 , -0.02697424],
       ...,
       [-0.38696772,  0.17490692,  0.30472568, ..., -0.1390576 ,
        -0.0646653 , -0.02697424],
       [ 0.67170039, -0.14910028,  0.31554996, ..., -0.1390576 ,
        -0.0646653 , -0.02697424],
       [ 0.67170039,  0.17490692,  0.32637425, ..., -0.1390576 ,
        -0.0646653 , -0.02697424]])

In [31]:
test_X_scaled = scaler.transform(X_test)

In [32]:
model = Ridge()
model.fit(train_X_scaled, y_train)

Ridge()

In [33]:
## R2 
print("사용한 데이터 컬럼 수 :", np.sum(model.coef_!=0))
print("훈련 데이터 셋 성능 : ", model.score(train_X_scaled, y_train))
print("테스트 데이터 셋 성능 : ", model.score(test_X_scaled, y_test))

사용한 데이터 컬럼 수 : 35
훈련 데이터 셋 성능 :  0.6847583554876444
테스트 데이터 셋 성능 :  0.6773316266005486

In [34]:
y_pred = model.predict(test_X_scaled)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(mse)
print(rmse)

44299770715.46297
210475.1071159318

In [35]:
# rmse 210,475으로 확인된다. 이는 예측값과 실제값과 210,475만큼 차이가 날 수 있다.

## 회귀 계수 중 집값과 상관성이 높은 3가지 변수를 해석하세요

In [36]:
coef = pd.DataFrame(model.coef_, index = X.columns, columns = ['coef'])
coef

                               coef
bedrooms              -19336.802850
bathrooms              35184.454079
sqft_living            54385.132770
sqft_lot                4653.662715
floors                 26818.938894
sqft_above             39655.716296
sqft_basement          38910.710848
yr_built              -92822.762187
yr_renovated            6238.879080
sqft_living15          24873.609551
sqft_lot15            -16295.698192
waterfront_river_view  21422.691933
waterfront_standard   -21422.691933
view_0                -15640.111028
view_1                  7926.912328
view_2                 -2695.157434
view_3                  6777.862875
view_4                 26766.428070
condition_1            -2450.295491
condition_2            -2976.483879
condition_3            -7443.124353
condition_4             1942.843515
condition_5            11407.695316
grade_1                 -784.811538
grade_3                -1219.793223
grade_4                -8784.551776
grade_5               -22972.264323
grade_6               -50947.047129
grade_7               -48151.403225
grade_8                -6245.327677
grade_9                41440.996297
grade_10               67106.606561
grade_11               76133.982911
grade_12               66508.596441
grade_13               50448.065555

In [37]:
coef['abs_coef'] = abs(coef.coef)
coef.sort_values('abs_coef', ascending = False)

                               coef      abs_coef
yr_built              -92822.762187  92822.762187
grade_11               76133.982911  76133.982911
grade_10               67106.606561  67106.606561
grade_12               66508.596441  66508.596441
sqft_living            54385.132770  54385.132770
grade_6               -50947.047129  50947.047129
grade_13               50448.065555  50448.065555
grade_7               -48151.403225  48151.403225
grade_9                41440.996297  41440.996297
sqft_above             39655.716296  39655.716296
sqft_basement          38910.710848  38910.710848
bathrooms              35184.454079  35184.454079
floors                 26818.938894  26818.938894
view_4                 26766.428070  26766.428070
sqft_living15          24873.609551  24873.609551
grade_5               -22972.264323  22972.264323
waterfront_standard   -21422.691933  21422.691933
waterfront_river_view  21422.691933  21422.691933
bedrooms              -19336.802850  19336.802850
sqft_lot15            -16295.698192  16295.698192
view_0                -15640.111028  15640.111028
condition_5            11407.695316  11407.695316
grade_4                -8784.551776   8784.551776
view_1                  7926.912328   7926.912328
condition_3            -7443.124353   7443.124353
view_3                  6777.862875   6777.862875
grade_8                -6245.327677   6245.327677
yr_renovated            6238.879080   6238.879080
sqft_lot                4653.662715   4653.662715
condition_2            -2976.483879   2976.483879
view_2                 -2695.157434   2695.157434
condition_1            -2450.295491   2450.295491
condition_4             1942.843515   1942.843515
grade_3                -1219.793223   1219.793223
grade_1                 -784.811538    784.811538

In [ ]:
# 가장 상관관계가 높은 변수는 yr_built, grade_11, grade_10 이다. 그러나  grade 10~12는 동일한 범주로, sqft_living 까지 
# 영향을 미치는 요소로 판단한다.